version: "3"

services:
  pollify-server:
    build: "."
    restart: "always"

    environment:
      - DATABASE=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@pollify-database:5432/${DATABASE_NAME}
      - SECRET=${SECRET}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - pollify-database

  pollify-database:
    image: "postgres:bullseye"
    restart: "always"

    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pollify-database:/var/lib/postgresql/data

volumes:
  pollify-database: